# Generated by Django 3.0.3 on 2020-02-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=50)),
                ('traxn_id', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50)),
                ('bank_id', models.CharField(max_length=50)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=50, null=True)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('access_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('statement_start_date', models.DateField(blank=True, null=True)),
                ('statement_end_date', models.DateField(blank=True, null=True)),
                ('pdf_url', models.CharField(blank=True, max_length=200, null=True)),
                ('excel_url', models.CharField(blank=True, max_length=200, null=True)),
                ('final_status', models.CharField(choices=[('1', 'Requested'), ('2', 'Processing'), ('3', 'Completed'), ('4', 'Failed')], max_length=1)),
                ('redirect_url', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionStatementDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traxn_id', models.CharField(max_length=50)),
                ('statement_id', models.CharField(max_length=50)),
                ('statement_date', models.CharField(blank=True, max_length=50, null=True)),
                ('statement_description', models.CharField(blank=True, max_length=50, null=True)),
                ('statement_category', models.CharField(blank=True, max_length=50, null=True)),
                ('statement_ref_no', models.CharField(blank=True, max_length=50, null=True)),
                ('statement_withdrawal_amt', models.CharField(blank=True, max_length=50, null=True)),
                ('statement_deposit_amt', models.CharField(blank=True, max_length=50, null=True)),
                ('statement_closing_balance', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionUserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traxn_id', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user_phone', models.IntegerField(blank=True, null=True)),
                ('user_email', models.CharField(blank=True, max_length=50, null=True)),
                ('user_pan', models.CharField(blank=True, max_length=50, null=True)),
                ('user_account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('user_adhar_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cif_number', models.CharField(blank=True, max_length=50, null=True)),
                ('micr_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
