# Generated by Django 3.0.3 on 2020-02-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trxn_token',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
