# Generated by Django 3.0.3 on 2020-02-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_trxn_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='product_id',
            new_name='loan_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='acceptance_policy',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='client_traxn_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='loan_duration',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='loan_type',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='product_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='traxn_id',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trxn_token',
            field=models.CharField(max_length=150),
        ),
    ]
