# Generated by Django 3.0.3 on 2020-02-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transactioncrawlerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncrawlerdata',
            name='captcha_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transactioncrawlerdata',
            name='otp_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transactioncrawlerdata',
            name='question',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncrawlerdata',
            name='user_captcha',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
