# Generated by Django 3.0.3 on 2020-02-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20200227_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='excel_url',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='pdf_url',
        ),
        migrations.AddField(
            model_name='transactionstatementdetail',
            name='excel_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transactionstatementdetail',
            name='pdf_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
