# Generated by Django 3.0.3 on 2020-02-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20200227_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactioncrawlerdata',
            name='captcha_type',
        ),
        migrations.RemoveField(
            model_name='transactioncrawlerdata',
            name='otp_type',
        ),
        migrations.AddField(
            model_name='transactioncrawlerdata',
            name='is_captcha_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactioncrawlerdata',
            name='is_otp_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactioncrawlerdata',
            name='is_quesiton_processed',
            field=models.BooleanField(default=False),
        ),
    ]
