# Generated by Django 3.0.3 on 2020-02-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_auto_20200227_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account_type',
        ),
        migrations.AddField(
            model_name='transactionuserdetail',
            name='user_account_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
