# Generated by Django 3.0.3 on 2020-02-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_auto_20200227_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionuserdetail',
            name='user_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
