# Generated by Django 3.0.3 on 2020-02-28 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_auto_20200227_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='final_status',
            new_name='traxn_status',
        ),
    ]
