# Generated by Django 3.0.3 on 2020-02-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_auto_20200228_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bank_ifsc_code',
        ),
        migrations.AddField(
            model_name='transactionuserdetail',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
