# Generated by Django 3.0.3 on 2020-02-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_auto_20200228_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionuserdetail',
            name='user_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='transactionuserdetail',
            name='user_city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transactionuserdetail',
            name='user_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactionuserdetail',
            name='user_state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transactionuserdetail',
            name='user_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactionuserdetail',
            name='user_pan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
