# Generated by Django 3.0.3 on 2020-03-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_auto_20200228_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trxn_attempt',
            field=models.IntegerField(default=0),
        ),
    ]
