# Generated by Django 3.0.3 on 2020-03-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_transaction_trxn_attempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traxn_id', models.CharField(max_length=20)),
                ('bank_id', models.CharField(max_length=20)),
                ('trxn_attempt', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='traxn_status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='trxn_attempt',
        ),
    ]
