# Generated by Django 3.0.3 on 2020-03-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0015_auto_20200305_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionattempt',
            old_name='trxn_attempt',
            new_name='traxn_attempt',
        ),
    ]
