# Generated by Django 3.0.3 on 2020-02-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200221_1251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bank',
            new_name='BankList',
        ),
    ]
