# Generated by Django 3.0.3 on 2020-02-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200221_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_code', models.CharField(max_length=10)),
                ('error_message', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
