# Generated by Django 3.0.3 on 2020-03-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20200302_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIEnity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=50)),
                ('entity_text', models.CharField(blank=True, max_length=350, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
