# Generated by Django 3.0.3 on 2020-02-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientaddress',
            name='city',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
