# Generated by Django 3.0.3 on 2020-02-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200220_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='exist_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
