# Generated by Django 3.0.3 on 2020-02-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20200220_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_person_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
