# Generated by Django 3.0.3 on 2020-02-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20200220_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
