# Generated by Django 3.0.3 on 2020-02-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20200220_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientproduct',
            name='client_redirect_url',
        ),
    ]
