# Generated by Django 3.0.3 on 2020-02-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20200221_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_logo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
